-- Add comprehensive sample data for student_data table
INSERT INTO student_data (title, details, course_category, photo_url, publish_date) VALUES
('Student Achievement Award 2024', 'Outstanding performance in Computer Science examinations with 95% marks achieved by Priya Sharma in ADCA course.', 'Advance Diploma In Computer Application(ADCA)', 'https://example.com/student-achievement1.jpg', '2024-08-15'),
('Top Scorer - Programming Contest', 'Rahul Kumar secured first position in National Level Programming Contest organized by our institute.', 'Post Graduate Diploma in Computer Application (PGDCA)', 'https://example.com/programming-winner.jpg', '2024-08-10'),
('Placement Success Story', 'Anjali Gupta successfully placed at TCS with 6 LPA package after completing DCA course from our institute.', 'Diploma in Computer Application (DCA)', 'https://example.com/placement-success.jpg', '2024-08-08'),
('Hardware Excellence Award', 'Suresh Patel demonstrated exceptional skills in computer hardware troubleshooting and networking configuration.', 'Diploma in Computer Hardware and Networking', 'https://example.com/hardware-excellence.jpg', '2024-08-05'),
('Academic Excellence - ADCA Batch', 'Complete ADCA batch of 2024 achieved 100% pass rate with average score of 88% in final examinations.', 'Advance Diploma In Computer Application(ADCA)', 'https://example.com/batch-excellence.jpg', '2024-08-01'),
('Industry Project Completion', 'Students successfully completed live industry project on E-commerce website development using modern technologies.', 'Post Graduate Diploma in Computer Application (PGDCA)', 'https://example.com/industry-project.jpg', '2024-07-28'),
('Certification Achievement', 'Batch of 25 students earned Microsoft Office Specialist certification along with their regular course completion.', 'Diploma in Computer Application (DCA)', 'https://example.com/certification.jpg', '2024-07-25'),
('Network Configuration Contest', 'Annual networking skills contest won by Networking students with perfect implementation of enterprise network setup.', 'Diploma in Computer Hardware and Networking', 'https://example.com/network-contest.jpg', '2024-07-20'),
('Alumni Success Story', 'Former student Vikash Singh now working as Software Engineer at Infosys shares his journey and tips for current students.', 'Advance Diploma In Computer Application(ADCA)', 'https://example.com/alumni-success.jpg', '2024-07-15'),
('Research Paper Publication', 'PGDCA students published research paper on "AI in Healthcare" in renowned international journal.', 'Post Graduate Diploma in Computer Application (PGDCA)', 'https://example.com/research-paper.jpg', '2024-07-10');